version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    container_name: auth
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      AUTH_HTTP_PORT: 3001

  users:
    build:
      context: .
      dockerfile: apps/users/Dockerfile
    container_name: users
    ports:
      - "3002:3002"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      USERS_HTTP_PORT: 3002

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    container_name: gateway
    ports:
      - "3000:3000"
    environment:
      AUTH_MICROSERVICE_HOST: auth
      AUTH_MICROSERVICE_PORT: 4001
      USERS_MICROSERVICE_HOST: users
      USERS_MICROSERVICE_PORT: 4002

volumes:
  mongodb_data: