version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_HOST=auth-service
      - USER_SERVICE_HOST=user-service
      - JWT_SECRET=your-very-secure-secret-key-here

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: auth
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/nest-microservices
      - JWT_SECRET=your-very-secure-secret-key-here

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: users
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/nest-microservices

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

volumes:
  mongodb_data: